const lessonTitle = "爱莲说";

const lessonData = [
    // ===== 第1段 =====
    ["水陆", "shuǐ lù", "Water and land", "Air dan darat"],
    ["草木", "cǎo mù", "plants", "tumbuhan"],
    ["之", "zhī", "", "", "的"],
    ["花", "huā", "flowers", "bunga-bungaan", "花"],
    ["，", "", "", "", ""],
    ["可爱者", "kě ài zhě", "lovable ones", "yang cantik", "值得喜爱的"],
    ["甚蕃", "shèn fán", "many", "banyak", "很多"],
    ["。", "", "", "", ""],
    ["晋", "jìn", "Jin Dynasty", "Dinasti Jin", "晋朝"],
    ["陶渊明", "táo yuān míng", "Tao Yuanming", "Tao Yuanming", "陶渊明"],
    ["独爱", "dú ài", "only loved", "hanya suka", "唯独喜爱"],
    ["菊", "jú", "chrysanthemums", "bunga kekwa", "菊花"],
    ["。", "", "", "", ""],
    ["自", "zì", "Since", "Sejak", "从"],
    ["李唐", "lǐ táng", "Tang Dynasty", "Dinasti Tang", "唐朝"],
    ["来", "lái", "", "", "以来"],
    ["，", "", "", "", ""],
    ["世人", "shì rén", "people", "orang ramai", "世人"],
    ["甚爱", "shèn ài", "greatly loved", "sangat suka", "非常喜爱"],
    ["牡丹", "mǔ dān", "peonies", "bunga peoni", "牡丹"],
    ["。", "", "", "", ""],
    ["予", "yú", "I", "Saya", "我"],
    ["独爱", "dú ài", "only love", "hanya suka", "唯独喜爱"],
    ["莲", "lián", "lotus", "bunga teratai", "莲花"],
    ["之", "zhī", "", "", "的"],
    ["出", "chū", "emerge", "keluar", "从……长出"],
    ["淤泥", "yū ní", "mud", "lumpur", "淤泥"],
    ["而", "ér", "and", "dan", "却"],
    ["不染", "bù rǎn", "not stained", "tidak tercemar", "不被沾染"],
    ["，", "", "", "", ""],
    ["濯", "zhuó", "washed", "membasuh", "洗涤"],
    ["清涟", "qīng lián", "clear ripples", "ombak jernih", "清水"],
    ["而", "ér", "and", "dan", "却"],
    ["不妖", "bù yāo", "not seductive", "tidak menggoda", "不妖媚"],
    ["，", "", "", "", ""],
    ["中通", "zhōng tōng", "hollow inside", "berongga di dalam", "中间贯通"],
    ["外直", "wài zhí", "straight outside", "lurus di luar", "外表挺直"],
    ["，", "", "", "", ""],
    ["不蔓", "bù màn", "no vines", "tiada sulur", "不牵牵连连"],
    ["不枝", "bù zhī", "no branches", "tiada ranting", "不枝枝节节"],
    ["，", "", "", "", ""],
    ["香远", "xiāng yuǎn", "fragrance spreads far", "harumnya jauh", "香气远播"],
    ["益清", "yì qīng", "more refined", "semakin harum", "更加清幽"],
    ["，", "", "", "", ""],
    ["亭亭", "tíng tíng", "elegantly", "dengan megah", "笔直地"],
    ["净植", "jìng zhí", "standing upright", "berdiri tegak", "洁净地立着"],
    ["，", "", "", "", ""],
    ["可", "kě", "can", "boleh", "可以"],
    ["远观", "yuǎn guān", "view from afar", "dilihat dari jauh", "远远地观赏"],
    ["而", "ér", "and", "dan", "却"],
    ["不可", "bù kě", "cannot", "tidak boleh", "不可以"],
    ["亵玩", "xiè wán", "play with disrespect", "dimainkan dengan tidak hormat", "轻慢地玩弄"],
    ["焉", "yān", "particle", "lah", "呢"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["予", "yú", "I", "Saya", "我"],
    ["谓", "wèi", "think", "berpendapat", "认为"],
    ["菊", "jú", "chrysanthemums", "bunga kekwa", "菊花"],
    ["，", "", "", "", ""],
    ["花之", "huā zhī", "flower of", "bunga yang", "花中的"],
    ["隐逸者也", "yǐn yì zhě yě", "recluse", "pertapa", "隐士"],
    ["；", "", "", "", ""],
    ["牡丹", "mǔ dān", "peonies", "bunga peoni", "牡丹"],
    ["，", "", "", "", ""],
    ["花之", "huā zhī", "flower of", "bunga yang", "花中的"],
    ["富贵者也", "fù guì zhě yě", "wealth and honour", "kekayaan dan kemuliaan", "富贵者"],
    ["；", "", "", "", ""],
    ["莲", "lián", "lotus", "bunga teratai", "莲花"],
    ["，", "", "", "", ""],
    ["花之", "huā zhī", "flower of", "bunga yang", "花中的"],
    ["君子者也", "jūn zǐ zhě yě", "gentleman", "orang berbudi", "君子"],
    ["。", "", "", "", ""],
    ["噫", "yī", "Alas", "Aduhai", "唉"],
    ["！", "", "", "", ""],
    ["菊之爱", "jú zhī ài", "love for chrysanthemums", "kasih pada bunga kekwa", "对菊花的喜爱"],
    ["，", "", "", "", ""],
    ["陶后", "táo hòu", "after Tao", "selepas Tao", "陶渊明之后"],
    ["鲜有闻", "xiǎn yǒu wén", "rarely heard of", "jarang didengar", "很少听说"],
    ["。", "", "", "", ""],
    ["莲之爱", "lián zhī ài", "love for lotus", "kasih pada bunga teratai", "对莲花的喜爱"],
    ["，", "", "", "", ""],
    ["同予者", "tóng yú zhě", "same as me", "sama seperti saya", "和我一样的"],
    ["何人", "hé rén", "who", "siapa", "有谁"],
    ["？", "", "", "", ""],
    ["牡丹之爱", "mǔ dān zhī ài", "love for peonies", "kasih pada bunga peoni", "对牡丹的喜爱"],
    ["，", "", "", "", ""],
    ["宜乎", "yí hū", "indeed", "memang", "当然"],
    ["众矣", "zhòng yǐ", "many", "ramai", "人很多"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["周敦颐", "zhōu dūn yí", "Zhou Dunyi", "Zhou Dunyi", "周敦颐"],
    ["《", "", "", "", ""],
    ["爱莲说", "ài lián shuō", "On the Love of the Lotus", "Mengenai Cinta Teratai", "爱莲说"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
